### ISSUE TITLE
Isssue with PHP 8.1

### ISSUE THREAD

**Issue by loranger** [TitasGailius/terminal#32]
Hello,

I use Terminal with Laravel-Zero, but it seems there is something broken since I updated PHP to version 8.1 

Here is the ouput I now get with my rsync command:

```bash
PHP Fatal error:  During inheritance of IteratorAggregate: Uncaught Error: Call to undefined method Psr\Log\NullLogger::channel() in /Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:96
Stack trace:
#0 /Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(71): Illuminate\Foundation\Bootstrap\HandleExceptions->handleDeprecation('Return type of ...', '/Users/loranger...', 106)
#1 /Users/loranger/Developer/projects/nas-cli/vendor/titasgailius/terminal/src/Response.php(10): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'Return type of ...', '/Users/loranger...', 106)
#2 /Users/loranger/Developer/projects/nas-cli/vendor/composer/ClassLoader.php(571): include('/Users/loranger...')
#3 /Users/loranger/Developer/projects/nas-cli/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/loranger...')
#4 /Users/loranger/Developer/projects/nas-cli/vendor/titasgailius/terminal/src/Builder.php(391): Composer\Autoload\ClassLoader->loadClass('TitasGailius\\Te...')
#5 /Users/loranger/Developer/projects/nas-cli/vendor/titasgailius/terminal/src/Builder.php(360): TitasGailius\Terminal\Builder->runProcess(Object(Symfony\Component\Process\Process))
#6 /Users/loranger/Developer/projects/nas-cli/vendor/titasgailius/terminal/src/Builder.php(333): TitasGailius\Terminal\Builder->execute(NULL, NULL)
#7 /Users/loranger/Developer/projects/nas-cli/app/Commands/Sync.php(46): TitasGailius\Terminal\Builder->run()
#8 /Users/loranger/Developer/projects/nas-cli/vendor/nunomaduro/laravel-console-task/src/LaravelConsoleTaskServiceProvider.php(49): App\Commands\Sync->App\Commands\{closure}()
#9 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/macroable/Traits/Macroable.php(124): App\Commands\Sync->NunoMaduro\LaravelConsoleTask\{closure}('Analyse des fic...', Object(Closure), 'v\xC3\xA9rification.....')
#10 /Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/src/Commands/Command.php(56): Illuminate\Console\Command->__call('task', Array)
#11 /Users/loranger/Developer/projects/nas-cli/app/Commands/Sync.php(48): LaravelZero\Framework\Commands\Command->task('Analyse des fic...', Object(Closure), 'v\xC3\xA9rification.....')
#12 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/container/BoundMethod.php(36): App\Commands\Sync->handle()
#13 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#15 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(LaravelZero\Framework\Application), Array, Object(Closure))
#16 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/container/Container.php(653): Illuminate\Container\BoundMethod::call(Object(LaravelZero\Framework\Application), Array, Array, NULL)
#17 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/console/Command.php(136): Illuminate\Container\Container->call(Array)
#18 /Users/loranger/Developer/projects/nas-cli/vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#19 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#20 /Users/loranger/Developer/projects/nas-cli/vendor/symfony/console/Application.php(1005): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /Users/loranger/Developer/projects/nas-cli/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(App\Commands\Sync), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /Users/loranger/Developer/projects/nas-cli/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/console/Application.php(94): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/src/Kernel.php(91): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /Users/loranger/Developer/projects/nas-cli/nas(37): LaravelZero\Framework\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 {main} in /Users/loranger/Developer/projects/nas-cli/vendor/titasgailius/terminal/src/Response.php on line 10

   Symfony\Component\ErrorHandler\Error\FatalError

  During inheritance of IteratorAggregate: Uncaught Error: Call to undefined method Psr\Log\NullLogger::channel() in /Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:96
Stack trace:
#0 /Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(71): Illuminate\Foundation\Bootstrap\HandleExceptions->handleDeprecation('Return type of ...', '/Users/loranger...', 106)
#1 /Users/loranger/Developer/projects/nas-cli/vendor/titasgailius/terminal/src/Response.php(10): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'Return type of ...', '/Users/loranger...', 106)
#2 /Users/loranger/Developer/projects/nas-cli/vendor/composer/ClassLoader.php(571): include('/Users/loranger...')
#3 /Users/loranger/Developer/projects/nas-cli/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/loranger...')
#4 /Users/loranger/Developer/projects/nas-cli/vendor/titasgailius/terminal/src/Builder.php(391): Composer\Autoload\ClassLoader->loadClass('TitasGailius\\Te...')
#5 /Users/loranger/Developer/projects/nas-cli/vendor/titasgailius/terminal/src/Builder.php(360): TitasGailius\Terminal\Builder->runProcess(Object(Symfony\Component\Process\Process))
#6 /Users/loranger/Developer/projects/nas-cli/vendor/titasgailius/terminal/src/Builder.php(333): TitasGailius\Terminal\Builder->execute(NULL, NULL)
#7 /Users/loranger/Developer/projects/nas-cli/app/Commands/Sync.php(46): TitasGailius\Terminal\Builder->run()
#8 /Users/loranger/Developer/projects/nas-cli/vendor/nunomaduro/laravel-console-task/src/LaravelConsoleTaskServiceProvider.php(49): App\Commands\Sync->App\Commands\{closure}()
#9 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/macroable/Traits/Macroable.php(124): App\Commands\Sync->NunoMaduro\LaravelConsoleTask\{closure}('Analyse des fic...', Object(Closure), 'v\xC3\xA9rification.....')
#10 /Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/src/Commands/Command.php(56): Illuminate\Console\Command->__call('task', Array)
#11 /Users/loranger/Developer/projects/nas-cli/app/Commands/Sync.php(48): LaravelZero\Framework\Commands\Command->task('Analyse des fic...', Object(Closure), 'v\xC3\xA9rification.....')
#12 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/container/BoundMethod.php(36): App\Commands\Sync->handle()
#13 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#15 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(LaravelZero\Framework\Application), Array, Object(Closure))
#16 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/container/Container.php(653): Illuminate\Container\BoundMethod::call(Object(LaravelZero\Framework\Application), Array, Array, NULL)
#17 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/console/Command.php(136): Illuminate\Container\Container->call(Array)
#18 /Users/loranger/Developer/projects/nas-cli/vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#19 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#20 /Users/loranger/Developer/projects/nas-cli/vendor/symfony/console/Application.php(1005): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /Users/loranger/Developer/projects/nas-cli/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(App\Commands\Sync), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /Users/loranger/Developer/projects/nas-cli/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/console/Application.php(94): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/src/Kernel.php(91): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /Users/loranger/Developer/projects/nas-cli/nas(37): LaravelZero\Framework\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 {main}

  at vendor/titasgailius/terminal/src/Response.php:10
      6▕ use Symfony\Component\Process\Process;
      7▕ use Symfony\Component\Process\Exception\ProcessFailedException;
      8▕ use TitasGailius\Terminal\Contracts\Response as ResponseContract;
      9▕
  ➜  10▕ class Response implements ResponseContract
     11▕ {
     12▕     /**
     13▕      * Process.
     14▕      *


   Whoops\Exception\ErrorException

  During inheritance of IteratorAggregate: Uncaught Error: Call to undefined method Psr\Log\NullLogger::channel() in /Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:96
Stack trace:
#0 /Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(71): Illuminate\Foundation\Bootstrap\HandleExceptions->handleDeprecation('Return type of ...', '/Users/loranger...', 106)
#1 /Users/loranger/Developer/projects/nas-cli/vendor/titasgailius/terminal/src/Response.php(10): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'Return type of ...', '/Users/loranger...', 106)
#2 /Users/loranger/Developer/projects/nas-cli/vendor/composer/ClassLoader.php(571): include('/Users/loranger...')
#3 /Users/loranger/Developer/projects/nas-cli/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/loranger...')
#4 /Users/loranger/Developer/projects/nas-cli/vendor/titasgailius/terminal/src/Builder.php(391): Composer\Autoload\ClassLoader->loadClass('TitasGailius\\Te...')
#5 /Users/loranger/Developer/projects/nas-cli/vendor/titasgailius/terminal/src/Builder.php(360): TitasGailius\Terminal\Builder->runProcess(Object(Symfony\Component\Process\Process))
#6 /Users/loranger/Developer/projects/nas-cli/vendor/titasgailius/terminal/src/Builder.php(333): TitasGailius\Terminal\Builder->execute(NULL, NULL)
#7 /Users/loranger/Developer/projects/nas-cli/app/Commands/Sync.php(46): TitasGailius\Terminal\Builder->run()
#8 /Users/loranger/Developer/projects/nas-cli/vendor/nunomaduro/laravel-console-task/src/LaravelConsoleTaskServiceProvider.php(49): App\Commands\Sync->App\Commands\{closure}()
#9 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/macroable/Traits/Macroable.php(124): App\Commands\Sync->NunoMaduro\LaravelConsoleTask\{closure}('Analyse des fic...', Object(Closure), 'v\xC3\xA9rification.....')
#10 /Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/src/Commands/Command.php(56): Illuminate\Console\Command->__call('task', Array)
#11 /Users/loranger/Developer/projects/nas-cli/app/Commands/Sync.php(48): LaravelZero\Framework\Commands\Command->task('Analyse des fic...', Object(Closure), 'v\xC3\xA9rification.....')
#12 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/container/BoundMethod.php(36): App\Commands\Sync->handle()
#13 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#15 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(LaravelZero\Framework\Application), Array, Object(Closure))
#16 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/container/Container.php(653): Illuminate\Container\BoundMethod::call(Object(LaravelZero\Framework\Application), Array, Array, NULL)
#17 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/console/Command.php(136): Illuminate\Container\Container->call(Array)
#18 /Users/loranger/Developer/projects/nas-cli/vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#19 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#20 /Users/loranger/Developer/projects/nas-cli/vendor/symfony/console/Application.php(1005): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /Users/loranger/Developer/projects/nas-cli/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(App\Commands\Sync), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /Users/loranger/Developer/projects/nas-cli/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /Users/loranger/Developer/projects/nas-cli/vendor/illuminate/console/Application.php(94): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /Users/loranger/Developer/projects/nas-cli/vendor/laravel-zero/framework/src/Kernel.php(91): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /Users/loranger/Developer/projects/nas-cli/nas(37): LaravelZero\Framework\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 {main}

  at vendor/titasgailius/terminal/src/Response.php:10
      6▕ use Symfony\Component\Process\Process;
      7▕ use Symfony\Component\Process\Exception\ProcessFailedException;
      8▕ use TitasGailius\Terminal\Contracts\Response as ResponseContract;
      9▕
  ➜  10▕ class Response implements ResponseContract
     11▕ {
     12▕     /**
     13▕      * Process.
     14▕      *

      +1 vendor frames
  2   [internal]:0
      Whoops\Run::handleShutdown()
```

I'm not sure the issue is coming from Terminal, but if you have any clue, I would be thankful !

**Comment by defunctl** [comment]
To just get your application running,  you can install the missing `illuminate\log` package in your Laravel Zero app, as it's trying to log deprecation notices for PHP 8.1: 

```shell
composer require illuminate/log
``` 

The notice fired for this specific project is:

```
"Return type of TitasGailius\Terminal\Response::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice"
"vendor/titasgailius/terminal/src/Response.php"
```

**Comment by loranger** [comment]
Thanks for this workaround. 
I can run my command now, but I think it would be better to fix the compatibility as I'm not supposed to install this package as log compatibility is a laravel zero plugin I don't need

**Comment by TitasGailius** [comment]
Fixed in https://github.com/TitasGailius/terminal/releases/tag/1.1.0
